### ISSUE TITLE
An error when excuting CEM_Example.ipynb

### ISSUE THREAD

**Issue by Vincant-Gan** [ido90/CeSoR#1]
A FileNotFoundError accured when excuting the In6 cell in CEM_Example.ipynb. 
I am told that "No such file or directory: 'models/CEM.cem'". 
And I noticed that there is a "models/" in the .gitignore file. Does the author forget to upload the models directory or something?

**Comment by sirish123** [comment]
@Vincant-Gan how did u resolve this issue

**Comment by Vincant-Gan** [comment]
> @Vincant-Gan how did u resolve this issue

i am sorry it is such a long time ago. could u please show me the detail?

**Comment by ido90** [comment]
@Vincant-Gan @sirish123 My apologies.

**The problem:**
Cell #4 attempts to save logs into models/CEM.cem, and fails because the directory does not exist.
Then cell #6 attempts to read these logs.

**The solution:**
Just create an empty directory named "models" under "Examples".
(I don't think I could upload an empty folder to github...).
I now added a more detailed error message.
